<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.1.1" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.1" />
		<PackageReference Include="AutoMapper" Version="15.1.0" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.7" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.7">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Scalar.AspNetCore" Version="2.11.6" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Gateway_API_Client\Gateway_API_Client.csproj" />
	</ItemGroup>

</Project>