// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251217091104_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Cars", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Compact sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/49440475318_2d9d3c994d_o.jpg",
                            Name = "Toyota Corolla",
                            Rate = 4.5,
                            price = 20000
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Sporty compact",
                            ImageUrl = "https://live.staticflickr.com/65535/52051754815_b5de4bea83_b.jpg",
                            Name = "Honda Civic",
                            Rate = 4.7000000000000002,
                            price = 22000
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Muscle car",
                            ImageUrl = "https://live.staticflickr.com/65535/52045457604_fc0a27e506_b.jpg",
                            Name = "Ford Mustang",
                            Rate = 4.9000000000000004,
                            price = 35000
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Performance coupe",
                            ImageUrl = "https://live.staticflickr.com/65535/52821278553_d03072cf41_b.jpg",
                            Name = "Chevrolet Camaro",
                            Rate = 4.7999999999999998,
                            price = 34000
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Luxury sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/51016184159_d0fc8847be_b.jpg",
                            Name = "BMW 3 Series",
                            Rate = 4.5999999999999996,
                            price = 42000
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Comfortable sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/50273443922_298b8bb6f8_b.jpg",
                            Name = "Audi A4",
                            Rate = 4.5,
                            price = 41000
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Premium sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/51818320308_1769ae013c_b.jpg",
                            Name = "Mercedes C-Class",
                            Rate = 4.5999999999999996,
                            price = 43000
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Electric sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/50195997318_00d4640d11_b.jpg",
                            Name = "Tesla Model 3",
                            Rate = 4.9000000000000004,
                            price = 50000
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Compact hatchback",
                            ImageUrl = "https://live.staticflickr.com/65535/50376941986_69e4f2056f_b.jpg",
                            Name = "Volkswagen Golf",
                            Rate = 4.2999999999999998,
                            price = 23000
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Details = "Midsize sedan",
                            ImageUrl = "https://live.staticflickr.com/65535/50733651236_abc123abcd_b.jpg",
                            Name = "Nissan Altima",
                            Rate = 4.2000000000000002,
                            price = 25000
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
